
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hruqrpbvbwafeyhuicmz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhydXFycGJ2YndhZmV5aHVpY216Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1NjA5NjQsImV4cCI6MjA2MTEzNjk2NH0.LP0w_ynhxUbKlJ1z12Sh-QTuosBzatznDW0IePskXEI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true
  }
});
